all:tracker

tracker: tracker.o commands.o
	g++ tracker.o commands.o -o  tracker

tracker.o: tracker.cpp
	g++ -c tracker.cpp

commands.o: commands.cpp
	g++ -c commands.cpp

r:
	rm tracker.o commands.o 
